site_name: Notes

theme:
  name: 'material'
  features:
    - instant
    - tabs

nav:
  - Home: index.md
  - Common: Common/README.md
  - DataBase: DataBase/README.md
  - FE: FE/README.md
  - Golang: Golang/README.md
  - Java: Java/README.md
  - Python: Python/README.md
  - Network: Network/README.md

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - def_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - footnotes
  - meta

