name: Build Github Pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install pygments pymdown-extensions
        pip install mkdocs mkdocs-material
        pip install mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin
    - name: Build Site
      run: mkdocs build
    - name: add CNAME file
      run: sh ./add-CNAME.sh
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@4
      with: 
        branch: gh-pages
        folder: site
